"""Add square category id

Revision ID: be9f49b4e6e1
Revises: 63d854032ab6
Create Date: 2024-12-23 19:09:06.478374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be9f49b4e6e1'
down_revision = '63d854032ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('square_environment', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('square_sandbox_access_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('square_sandbox_location_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('square_production_access_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('square_production_location_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('square_production_location_id')
        batch_op.drop_column('square_production_access_token')
        batch_op.drop_column('square_sandbox_location_id')
        batch_op.drop_column('square_sandbox_access_token')
        batch_op.drop_column('square_environment')

    # ### end Alembic commands ###
