"""initial_migration

Revision ID: f5ced2dbb283
Revises: 
Create Date: 2024-12-27 04:41:42.217687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5ced2dbb283'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote_record')
    op.drop_table('feature_request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_request',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('feature_request_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('upvotes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('downvotes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='feature_request_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('vote_record',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feature_request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_cookie', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('vote_type', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['feature_request_id'], ['feature_request.id'], name='vote_record_feature_request_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='vote_record_pkey'),
    sa.UniqueConstraint('feature_request_id', 'user_cookie', name='unique_user_vote')
    )
    # ### end Alembic commands ###
